### ISSUE TITLE
Custom options for Group

### ISSUE THREAD

**Issue by sarates** [HubSpot/react-select-plus#102]
How should I pass options to Select for USERS GROUP with this data structure?

`{
  "groups": [
    {
      "id": "3124123123",
      "name": "CSD IT Apps",
      "users": [
        {
          "id": "992694534",
          "timezone": "Europe/Berlin",
          "name": "John Doe",
          "profileImage": "https://randomuser.me/api/portraits/men/78.jpg"
        },`

**Comment by TrevorBurnham** [comment]
See this example: https://github.com/HubSpot/react-select-plus#option-groups

**Comment by sarates** [comment]
So I cant conf it with "groups" and "users" labels? Always key "options" should be?

**Comment by sarates** [comment]
Or I should map my data  to 'options' keys, not groups / users
