### ISSUE TITLE
Please update to react-select 1.2.0

### ISSUE THREAD

**Issue by danez** [HubSpot/react-select-plus#105]
:)

**Comment by tomxhu** [comment]
Specifically this PR fixes an issue where multiple dropdowns can be open at once: https://github.com/JedWatson/react-select/pull/2213

**Comment by TrevorBurnham** [comment]
We attempted the update, but ran into some tricky merge conflicts that have yet to be worked out. We'll try to get through them.

In the meantime, you might want to check out the alpha of [react-select v2](https://github.com/JedWatson/react-select/tree/v2.0.0-alpha.5), which adds option group support. If that release works well, we'll be discontinuing this fork.
