### ISSUE TITLE
Using '&times;' causes character encoding issues in some cases

### ISSUE THREAD

**Issue by maggiewes** [HubSpot/react-select-plus#11]
We used String.fromCharCode(215) for the 'x' (times) symbol and the problem went away. I've attached a screenshot of the issue.

I'm submitting a PR for it. If you think there's a better way to tackle this just let me know.

Thanks!

![screen shot 2016-04-06 at 1 54 29 pm](https://cloud.githubusercontent.com/assets/1205095/14333019/4fe522aa-fc01-11e5-87d2-521a6ba994b1.png)

**Comment by TrevorBurnham** [comment]
See my comment at https://github.com/HubSpot/react-select-plus/pull/12#issuecomment-207058712
