### ISSUE TITLE
Non-clearable Selects can be cleared (with backspace)

### ISSUE THREAD

**Issue by dylanscott** [HubSpot/react-select-plus#112]
I'm not sure if this is intentional, but it was certainly very unexpected for me. Selects with `clearable={false}` can be cleared by hitting backspace while the input is focused. This can easily be reproduced on the [demo page](http://github.hubspot.com/react-select-plus/) by unchecking clearable on the first example.

**Comment by TrevorBurnham** [comment]
Yes, `clearable` only means that the "x" icon is shown. You can control the backspace behavior with the `backspaceRemoves` prop.

This API is from react-select, so we don't intend to change it.
