### ISSUE TITLE
future?

### ISSUE THREAD

**Issue by vgoklani** [HubSpot/react-select-plus#14]
Is the plan to keep this project separate and distinct from react-select, or is it eventually going to get merged back.

**Comment by TrevorBurnham** [comment]
I'd be happy to see the added features in this project merged in to react-select, but ultimately that's up to the react-select maintainers. Until then, I intend to maintain this fork.

**Comment by oyeanuj** [comment]
@TrevorBurnham Appreciate you adding more to react-select. Is it possible to have a short summary of what all features does it have in addition to the original react-select library?

**Comment by TrevorBurnham** [comment]
Currently, react-select-plus has these features that react-select does not have:

1. **Most important:** Support for option groups (https://github.com/HubSpot/react-select-plus/pull/3)
1. The dropdown can be a custom component, e.g. allowing it to be rendered in a `position: fixed` container to avoid z-index issues: https://github.com/HubSpot/react-select-plus/pull/2
1. If `value` does not match any option, the value can be displayed: https://github.com/HubSpot/react-select-plus/pull/9
1. You can override the open/closed state of the dropdown: https://github.com/HubSpot/react-select-plus/pull/1
