### ISSUE TITLE
Peer dependencies have stopped matching minor versions of react and react-dom - i.e. 15.0.1

### ISSUE THREAD

**Issue by mattics** [HubSpot/react-select-plus#20]
The change from "^15.0.0" to "^15.0" as a required version has stopped 15.0.1 / 15.0.2  etc being matched.

Suggest reverting just the peerDependencies for react and react-dom to "^15.0.0".

I can submit a PR for this, but wasn't sure if it was intentional or already on your radar. I'm sure by the time you have read this you will have fixed it anyway.

**Comment by TrevorBurnham** [comment]
This change was made upstream: https://github.com/JedWatson/react-select/commit/33a1af11a28ee4b2581956a2c8caa7fa300cda7f I'd prefer not to deviate from the upstream on matters unrelated to the features added by this fork.

Is it possible that you're using an old version of npm? If you use the [http://semver.npmjs.com/](npm semver calculator), enter "react" as the package and "^15.0" as the range, you'll see that 15.0.1 and 15.0.2 are indeed matched.

**Comment by mattics** [comment]
Very strange, it is now working as expected. I honestly tried it several times and got the same error that the requirement of ^15.0 was not satisfied by 15.0.2 each time so assumed that not specifically including the minor version in the requirement caused the error.

I am on node 4.4.4 (npm 2.5.1) and definitely haven't updated it since trying it earlier. It is possible I have had PhpStorm open for several weeks and so it's terminal was not running the latest... I wouldn't have thought so though.

Apologies for the false issue :)
