### ISSUE TITLE
[1.0.0-beta13] Async options with Promises displays [object Promise] as input value

### ISSUE THREAD

**Issue by szymonmichalak** [HubSpot/react-select-plus#24]
Hey,
I am having an issue with `1.0.0-beta13` version, as with Async options whenever user tries to write something in the input, it changes typed value to `[object Promise]`. There is already a fix for that at `react-select` - is there any chance to merge this fix to `react-select-plus` and publish a new version to npm?

Issue on `react-select`:
https://github.com/JedWatson/react-select/issues/940

Pull Request fixing that issue:
https://github.com/JedWatson/react-select/pull/941

Thanks!

**Comment by TrevorBurnham** [comment]
I'm aware of the issue. Unfortunately, there hasn't been a react-select release with that patch yet, and I've been trying to keep react-select-plus releases in 1:1 correspondence with react-select releases. This seems like a good case for an exception, though. I'll put together an intermediate release later today.

**Comment by TrevorBurnham** [comment]
I've published a release with that patch as `1.0.0-beta13.patch`.

**Comment by szymonmichalak** [comment]
Wow, that was quick! Thank you so much, works like a charm 👍
