### ISSUE TITLE
Focused item in group not visible when opening select

### ISSUE THREAD

**Issue by Mesoptier** [HubSpot/react-select-plus#27]
The menu will scroll to the top of the option group instead of to the focused item. This means that sometimes (a.k.a. always with more than about 5 items) the focused item will not be visible, which is not desirable at all. See this plknr: https://embed.plnkr.co/4NgjYpGQ3xh4YBEtUYEd/

This issue is directly caused by https://github.com/HubSpot/react-select-plus/issues/17 (af040a6c085ea73c2da0bd24ab48a22ebd58c675).

**Comment by TrevorBurnham** [comment]
I agree: https://github.com/HubSpot/react-select-plus/issues/17#issuecomment-232759116

**Comment by Mesoptier** [comment]
This fix has not been persisted to the files in the `lib/` directory, therefore it will not actually work for people who require/import the package.

**Comment by TrevorBurnham** [comment]
Ooph, right you are. I've done a build and pushed to master, which I've tagged as v1.0.0-beta14: 3322f48 Unfortunately there's no way to update the npm package for that version. I'll publish a patch release to npm later today.
