### ISSUE TITLE
minWidth on <input> tag is invalid

### ISSUE THREAD

**Issue by vaibhav-495** [HubSpot/react-select-plus#29]
getting this error:

"en_US.Main.js:22103 Warning: Unknown prop `minWidth` on <input> tag. Remove this prop from the element."

also referenced here [#1063](https://github.com/JedWatson/react-select/issues/1063)

**Comment by TrevorBurnham** [comment]
This will be fixed when I merge in the latest react-select-plus release (likely later this week).

**Comment by bdefore** [comment]
This warning also occurs on the 0.9.1 version

**Comment by TrevorBurnham** [comment]
This should now be fixed.
