### ISSUE TITLE
Scroll to first option group when open dropdown

### ISSUE THREAD

**Issue by Arkayus** [HubSpot/react-select-plus#31]
I want the multi react-select to scroll to the first option group when I've never click on one of the options.
Currently, it scroll to the first item, so I don't see the option group.

**Comment by TrevorBurnham** [comment]
@Arkayus I'm not seeing this bug. Are you using the latest release (`v1.0.0-beta14.patch1`)?

**Comment by TrevorBurnham** [comment]
Closing, but reopen if you can provide steps to replicate in the latest release.
