### ISSUE TITLE
Options are not remove from the dropdown when select them

### ISSUE THREAD

**Issue by Arkayus** [HubSpot/react-select-plus#32]
I have setup a multiselect with group and when i select a item in the list, it is not remove from it.
When my select is not a multiselect, it work fine.

**Comment by TrevorBurnham** [comment]
I'm not seeing this. Are you using the latest release (`v1.0.0-beta14.patch1`)?

![sep-08-2016 17-08-18](https://cloud.githubusercontent.com/assets/224895/18366979/da4900ba-75e6-11e6-9652-044a541a28bf.gif)
