### ISSUE TITLE
react-select leaving out a particular option

### ISSUE THREAD

**Issue by Ice32** [HubSpot/react-select-plus#35]
I'm having this weird bug, I don't know if I'm doing something wrong. It seems like something related to asynchronous data loading, but I don't know how to debug this.

I'm using **react-select-plus 1.0.0-beta14 with google place autocomplete API**, but I can't get a particular location to show immediately (and I really need that location to display).  I'm loading the data asynchronously using "loadOptions" and promises. Google place autocomplete API always returns 5 locations, but for some reason, for a particular input, **react-select displays only 4 even though if I write out options in the loadOptions promise, all 5 are there**. Also, if, after only those 4 values are displayed, **I click somewhere else so that the react-select loses focus and dropdown options are hidden, when I click on the react-select's input field again so that the dropdown values display again, all 5 are there as they should be**.  Keep in mind that **it's always leaving out the same option**. I haven't noticed it with any other location.  Here's my code:
```
loadAutocomplete(input){
        let fetchUrl = baseUrl + "api/services/google/autocomplete?input=" + input;
        fetchUrl = encodeURI(fetchUrl);
        return fetch(fetchUrl, {method:"get", headers:{"Content-Type":"application/json"}})
            .then( response => response.json())
            .then(suggestions => {
                console.log(suggestions);   //WRITES OUT CORRECT LOCATIONS (ALL 5)
                return ({options:suggestions});
            })
    }
```

Options I console.log() before returning the from promise (the second one is the one that gets left out):
```
[
  {
    "label": "Hostal Sol Madrid, Calle Marqués Viudo de Pontejos, Madrid, Spain",
    "value": "ChIJbz9ISX4oQg0Rq2taBHu-DBA"
  },
  {
    "label": "Sol, Madrid, Spain",
    "value": "ChIJf-YYGX4oQg0RRvnJ0KBzhDM"
  },
  {
    "label": "Sol Pelícanos Ocas, Calle Gerona, Benidorm, Spain",
    "value": "ChIJo73enFcEYg0RvN7lZs3Ygik"
  },
  {
    "label": "Sol Duc Hot Springs Resort, Port Angeles, WA, United States",
    "value": "ChIJq6YwIPBEjlQRVeg28xhFwrU"
  },
  {
    "label": "Sol Principe, Torremolinos, Spain",
    "value": "ChIJDdCCJOj7cg0RjqFJincQ65E"
  }
]
```

[On input screenshot](http://oi66.tinypic.com/103he9z.jpg)
[lose focus and then refocus again screenshot](http://oi63.tinypic.com/ixf1uf.jpg)

**Comment by TrevorBurnham** [comment]
That's alarming. Have you tried replicating with react-select? It doesn't look like you're using any react-select-plus functionality here.

By the way, you can drag screenshots into the comment box in GitHub to post them directly in your comment, rather than relying on an external image host like TinyPic. Also, I recommend using [LICEcap](http://www.cockos.com/licecap/) to capture animated GIFs of behavioral bugs.

**Comment by Ice32** [comment]
I have tried using react-select and the same thing is happening. It also seems that google API has now started returning this same location name two times , so these are the options I'm passing to react-select:

```
[
  {
    "label": "Sol, Madrid, Spain",
    "value": "ChIJf-YYGX4oQg0RRvnJ0KBzhDM"
  },
  {
    "label": "Sol Duc Hot Springs Resort, Port Angeles, WA, United States",
    "value": "ChIJq6YwIPBEjlQRVeg28xhFwrU"
  },
  {
    "label": "Sol, Madrid, Spain",
    "value": "ChIJz7ZjFH4oQg0RYS0zuSBBoxQ"
  },
  {
    "label": "Hostal Sol Madrid, Calle Marqués Viudo de Pontejos, Madrid, Spain",
    "value": "ChIJbz9ISX4oQg0Rq2taBHu-DBA"
  },
  {
    "label": "Sol Food - Mill Valley, Miller Avenue, Mill Valley, CA, United States",
    "value": "ChIJCbkidKiahYARNoq7GZf-2YM"
  }
]
```

Again, none of the "Sol, Madrid" options display, only the 3 other options.

Also, thanks for the tips.

**Comment by TrevorBurnham** [comment]
> I have tried using react-select and the same thing is happening.

I'd suggest filing a ticket on [react-select](https://github.com/JedWatson/react-select), then. Any patches committed there will be merged in to the next react-select-plus release.

You might want to see if overriding `filterOptions` lets you prevent the option from being filtered. This ticket may be relevant: https://github.com/JedWatson/react-select/issues/1097

Beyond that, it's hard for me to understand how what you're describing could happen, so see if you can create a [CodePen](http://codepen.io/) that replicates the behavior.
