### ISSUE TITLE
Cannot

### ISSUE THREAD

**Issue by asafshen** [HubSpot/react-select-plus#38]
Hi,

Im trying to make an `Select` component that integrate with [React-Formsy](https://github.com/christianalfoni/formsy-react).

in order to do so - I want to pass the `<input ../>` component an `required=true` property (supported via select's `inputProps`).

```
<Select
    name="form-field-name"
    value="one"
    options={options}
    onChange={logChange}
     inputProps={{
              required: true,
              otherField: true
      }}

  />

var options = [
    { value: 'one', label: 'One' },
    { value: 'two', label: 'Two' }
];

function logChange(val) {
    console.log("Selected: " + val);
}
```

When I inspect the components in react chrome debugger - I can see that `otherField: true` but `required: false`.

As a matter of fact - all other props are propagated well to `<input>` except required.

Any Suggestions?

Thanks.

**Comment by TrevorBurnham** [comment]
Yes, `required` is indeed overridden by react-select: https://github.com/HubSpot/react-select-plus/blob/731c2a5f23e5babff2f294a0c1f9ccfeff24b3a2/src/Select.js#L810 You can't control it directly. You can only set `required={true}` on the `<Select>` component, in which case `required` will be `true` on the `<input>` if and only if [no value is set](https://github.com/HubSpot/react-select-plus/blob/731c2a5f23e5babff2f294a0c1f9ccfeff24b3a2/src/Select.js#L510-L513).
