### ISSUE TITLE
Include `name` property in `onChange(selected)` 

### ISSUE THREAD

**Issue by jfsiii** [HubSpot/react-select-plus#49]
This would make it easier to use a single `onChange` handler for tracking current state.

e.g. The same change handler 

```
const onChange = (selected) => {
  this.setState({ [selected.name]: selected.value })
}
```

Could be used for

```
<Select
    name="form-field-name-one"
    value="one"
    options={optionsForOne}
    onChange={onChange}
  />

<Select
    name="form-field-name-two"
    value="two"
    options={optionsForTwo}
    onChange={onChange}
  />
```

**Comment by TrevorBurnham** [comment]
I don't want to create any unnecessary API differences between this project and react-select. I'd like for it to be a drop-in replacement in most cases; changing the argument signature of `onChange` would prevent that.

**Comment by jfsiii** [comment]
My current workaround is to create a handler which uses a closure to track the name.

```javascript
_createChangeHandler(name) {
  const onChange = (newValue) => this.setState({ [name]: newValue.value });
  return onChange;
}

const onChange = this._createChangeHandler(name);
return (
  <Select
    name={name}
    value={this.state[name]}
    onChange={onChange}
    ...
  />
);
```

**Comment by jfsiii** [comment]
Opened an issue upstream https://github.com/JedWatson/react-select/issues/1458
