### ISSUE TITLE
Select Multiple height when initially loaded vs. populated

### ISSUE THREAD

**Issue by tsnevillecom** [HubSpot/react-select-plus#50]
I have an interface that loads preselected options inside a multi-select box. When react is loading the element, the height seems to be determined on an empty select box, which then renders other elements on top or below the select box. When I do anything to either element, react re-renders them, and then they look fine. Any ideas?

**This is wrong...**
![screen shot 2016-12-29 at 8 11 01 am](https://cloud.githubusercontent.com/assets/3151454/21544641/f582c90a-cd9e-11e6-9ed3-1a0758235d81.png)

**This is right!**
![screen shot 2016-12-29 at 8 11 17 am](https://cloud.githubusercontent.com/assets/3151454/21544644/f8e6132c-cd9e-11e6-90b2-2643a5d891c7.png)

**Comment by TrevorBurnham** [comment]
Hmm. I'm not sure exactly what's going on here, but I've seen similar artifacts happen as a result of the autosized input. See if you still experience the issue if you set

```
autosize={false}
```

If it is autosize-related, try passing in

```js
inputProps={{onAutosize: this.forceUpdate}}
```

**Comment by TrevorBurnham** [comment]
Closing this out. Please reopen if you can create an example I can replicate.

**Comment by FranDias** [comment]
@tsnevillecom Are you using flexbox for positioning by any chance?

**Comment by tsnevillecom** [comment]
@FranDias Yes. Sorry for the delay.
