### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by ehartford** [HubSpot/react-select-plus#52]
Please fork the react-select typescript typings from

[@types/react-select](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-select)

into

@types/react-select-plus

and add any modifications

**Comment by TrevorBurnham** [comment]
I'm not very familiar with TypeScript. If you'd like to contribute those TypeScript annotations yourself, I'd be happy to see them.
