### ISSUE TITLE
Multiselect disable option should remove the disabled option if it's already selected

### ISSUE THREAD

**Issue by yonatanmk** [HubSpot/react-select-plus#55]
In the live demo, if a user were to add chocolate to the multiselect input and then disable the chocolate option, chocolate would remain in the in the input field with the nex label text as so:

<img width="428" alt="screen shot 2017-02-26 at 3 15 16 pm" src="https://cloud.githubusercontent.com/assets/20758953/23343275/90d5b0a0-fc36-11e6-9dc5-b5e94417d885.png">

Shouldn't chocolate be removed from the input should the user disable the chocolate option?

**Comment by TrevorBurnham** [comment]
This is the same behavior as in the upstream React Select project: http://jedwatson.github.io/react-select/

I see what you're saying, but the component isn't so opinionated as to hide options that are included in its `values`. The visible component state is a 1:1 reflection of the `values` prop. If an app wants to include an option that can be removed but not re-added, that's weird but it's not technically prohibited.
