### ISSUE TITLE
Text in input not selectable

### ISSUE THREAD

**Issue by khenlevy** [HubSpot/react-select-plus#57]
found a fix, didn't pass tests.
https://github.com/Reggino/react-select/commit/b55843ff02be964ba39491561d8645be5de5654d

לֹan we have a solution for having a Input Text behavior?

**Comment by TrevorBurnham** [comment]
Unfortunately, this behavior is baked pretty deeply into react-select. I don't want to diverge too much from the upstream project by changing it.
