### ISSUE TITLE
Dropdowns Need To Be Clicked Twice: Patch3

### ISSUE THREAD

**Issue by kylemcclendon** [HubSpot/react-select-plus#61]
When using version 1.0.0-rc.3.patch3, it seems the Select fields now require 2 clicks to activate the dropdown showing the options. The first one focuses on the field, the second click actually opens the dropdown. This can even be seen on the examples page: http://github.hubspot.com/react-select-plus/. All those examples (except for the Cities (Large Dataset) example) require 2 clicks for the dropdown to appear.

Please let me know if this is intended or a bug. Thanks!

**Comment by davidpaulmcintyre** [comment]
i think that that is the default behavior, but you can override it by setting openOnFocus = {true}.  But i found that autofocus needs to be turned off b/c otherwise the dropdown opens when the component loads

**Comment by kylemcclendon** [comment]
@davidpaulmcintyre Ah, you are correct. Looks like it came from react-select being merged into react-select-plus. It was brought up by some people who found it annoying to double click in a project of ours. Thanks for pointing that out! I'll close this as it's not an issue.

**Comment by davidpaulmcintyre** [comment]
For anyone else who encounters this problem, be aware that setting autoFocus = true results in the select component occasionally receiving focus and popping open when it shouldn't, such as after an alert box pops up and is then closed.

**Comment by TrevorBurnham** [comment]
> Looks like it came from react-select being merged

Confirmed, same behavior is present in the current `master` of React-Select. Not sure whether that was intended or not (it does strike me as strange), but I've been trying to diverge from the upstream project as little as possible.
