### ISSUE TITLE
Add ability to change opt-group delimiter

### ISSUE THREAD

**Issue by th3fallen** [HubSpot/react-select-plus#63]
Would be super neat if we could pass a prop to change the default delimiter for opt-groups from `options` to say `children` or anything else for that matter.

**Comment by TrevorBurnham** [comment]
This would complicate the `unflattenOptions` logic a bit. Currently, each "tree" is assumed to have its children in an array called `options`. With this change, it would have to check on each iteration: "Is this tree the root? If so, its children are in `tree.options`; if not, its children are in `tree[childOptionsKey]`." I'm not sure the added flexibility is worth the added complexity.
