### ISSUE TITLE
possible to select opt-group with value?

### ISSUE THREAD

**Issue by th3fallen** [HubSpot/react-select-plus#64]
from your example you have opt-groups with a `label` and one with both a `label` and `value` is there some way im missing to add the ability to select an opt-group if it contains a value?

**Comment by TrevorBurnham** [comment]
No, the `value` field is meaningless for opt-groups. Which example are you referring to?

**Comment by th3fallen** [comment]
ah, i misread, i saw the `black` option and thought it was a opt-group header....

**Comment by th3fallen** [comment]
actually on this topic, would it be at all possible to make the opt-group itself selectable if it contained a value? it's kind of an edge case but would be immensely helpful
