### ISSUE TITLE
It is already not working

### ISSUE THREAD

**Issue by yashchenko-roi** [HubSpot/react-select-plus#67]
ERROR in ./node_modules/react-input-autosize/lib/AutosizeInput.js
Module not found: Error: Can't resolve 'create-react-class' in '/home/.../node_modules/react-input-autosize/lib'
 @ ./node_modules/react-input-autosize/lib/AutosizeInput.js 7:18-47
 @ ./node_modules/react-select-plus/lib/Select.js
...

**Comment by Friss** [comment]
Looks like there was a breaking change in the latest react-input-autosize that switched to using create-react-class but didn't add it as a dependency. https://github.com/JedWatson/react-input-autosize/issues/84

There is a solution for this error in that issue that you can use. 

@TrevorBurnham should we pin the autosize dep to before the breaking change?
