### ISSUE TITLE
Deprecation warning about PropTypes

### ISSUE THREAD

**Issue by guillaume86** [HubSpot/react-select-plus#69]
Here's the messages:

Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

AsyncCreatableSelect: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by hans-lizihan** [comment]
https://github.com/JedWatson/react-select/pull/1658/files

**Comment by TrevorBurnham** [comment]
Fixed by #75 and released as v1.0.0-rc.5.
