### ISSUE TITLE
Create value to become first item- `showNewOptionAtTop` prop

### ISSUE THREAD

**Issue by yarnball** [HubSpot/react-select-plus#70]
Hi,

Great work on this.

I would like to make it so "Create" is not the first/auto highlighted option when a user starts typing. 

According the the main (non-plus of `react-select`) it was put in this commit ([here](https://github.com/JedWatson/react-select/commit/9c963d0593396904676e92f09903710f75fa9d0c)). How can I integrate this feature myself?

I created a screenshot to help explain.

![screen shot 2017-05-14 at 9 34 54 pm](https://cloud.githubusercontent.com/assets/13043067/26033393/bffbaf52-38ee-11e7-9773-b9308f40e839.jpg)

**Comment by TrevorBurnham** [comment]
That commit is part of a PR that hasn't been merged yet: https://github.com/JedWatson/react-select/pull/1436 If it's merged, it'll become part of react-select-plus, so keep an eye on that ticket.
