### ISSUE TITLE
Double click for expanding

### ISSUE THREAD

**Issue by alrms** [HubSpot/react-select-plus#72]
### Thanks for using react-select!

If you are reporting an error please include a test case that demonstrates the issue you're reporting!
This is very helpful to maintainers in order to help us see the issue you're seeing.

Here is a Plunker you can fork that has react-select loaded and supports JSX syntax:
https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

You may also find the [online Babel tool](https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

**Comment by alrms** [comment]
I'm using react-select plus in my project. It requires double click for collapsing unlike the react-select.

**Comment by TrevorBurnham** [comment]
@alrms I've never seen the behavior you're describing. Can you provide a complete example, or an animated GIF?

**Comment by alrms** [comment]
I'll show you. This fact is also happening in react-select-plus demo. When i enter the page the react-select-components require one click for focusing and then another click for collapsing

**Comment by alrms** [comment]
Excuse me, i was wrong. The react-select-plus component requires double click for expanding. Not for collapsing

**Comment by alrms** [comment]
This the gif for the issue i was refering to
![webp net-gifmaker](https://cloud.githubusercontent.com/assets/28054369/26295931/0fe638ac-3ed5-11e7-802a-b421d75bceac.gif)

**Comment by TrevorBurnham** [comment]
@alrms Ah, yes. I did a bisect, and it looks like this was introduced by an upstream change: https://github.com/JedWatson/react-select/pull/1527 It's been since fixed in JedWatson/react-select, so that fix should carry over once I merge in the latest tagged release (probably later this week).

**Comment by TrevorBurnham** [comment]
As a temporary workaround, you might want to consider setting `openOnFocus={true}`.

**Comment by alrms** [comment]
A thanks for the quick response @TrevorBurnham :) Please keep me inform when you merge the latest tagged release so as to update my component via npm :)

**Comment by TrevorBurnham** [comment]
1.0.0-rc.4 has been published.

**Comment by alrms** [comment]
@TrevorBurnham Hello again. I update my react-select-plus component from rc-4.0 to rc-5 version and the issue i opened was returned. Can you check it out?
