### ISSUE TITLE
React-select-plus component requires double click for expanding after updating in version 5.0

### ISSUE THREAD

**Issue by alrms** [HubSpot/react-select-plus#77]
@TrevorBurnham, yesterday i updated my react-select-plus module from version 4.0 to version 5.0 and the issue came back. Can you ckeck it out?

**Comment by TrevorBurnham** [comment]
I'm unable to replicate. I've updated the example page to use the latest release, and everything on the page opens with a single click: http://github.hubspot.com/react-select-plus/
