### ISSUE TITLE
ignoreCase results in bad user experience

### ISSUE THREAD

**Issue by tjveldhuizen** [HubSpot/react-select-plus#79]
When using the (default enabled) ignoreCase option, the user input is converted to lowercase in the input box. I'ld prefer to leave the input as entered by the user, while converting it to lowercase when performing the search. In the current situation my users are surprised by the fact that their input is modified (checking if their caps lock key is activated...)

**Comment by TrevorBurnham** [comment]
> When using the (default enabled) ignoreCase option, the user input is converted to lowercase in the input box.

I'm not seeing what you're describing. Can you replicate this behavior in any of the examples at http://github.hubspot.com/react-select-plus/?

**Comment by tjveldhuizen** [comment]
It appears to be happening only in the asynchronous select box: try typing some capitals in the "Contributors (Async)" example.

**Comment by TrevorBurnham** [comment]
Ah. Looks like this is a known bug in the upstream project: https://github.com/JedWatson/react-select/issues/1352

**Comment by zldavis** [comment]
Looks like this was fixed, any plans to pick up the change?

https://github.com/JedWatson/react-select/pull/1858

**Comment by TrevorBurnham** [comment]
Yes, we're still trying to keep react-select-plus up-to-date against the upstream project. Just haven't been able to perform that update yet.

**Comment by zldavis** [comment]
great, thanks for the response!
