### ISSUE TITLE
"Clear" button is displayed when default option is selected

### ISSUE THREAD

**Issue by aem** [HubSpot/react-select-plus#8]
I would assume the default behavior would be when the `defaultValue` is selected the clear button would not be displayed, but based on my initial tests this isn't true:

<img width="199" alt="screen shot 2016-04-01 at 9 58 41 am" src="https://cloud.githubusercontent.com/assets/1909883/14209074/71748f60-f7f0-11e5-93f8-6c54f5965eb9.png">

**Comment by TrevorBurnham** [comment]
The `defaultValue` you're referring to would more accurately be called the "initial value." Having an initial value does not preclude the control from having no value entirely, which is what the "clear" button does.

If you want to prevent the user from clearing the value, use the `clearable={false}` prop.
