### ISSUE TITLE
Collapse is not showing value when i'm giving inpu

### ISSUE THREAD

**Issue by alrms** [HubSpot/react-select-plus#80]
Hello everyone, i'm using react-select-plus and redux saga for calling a service. My code is here:
<Select
            id="portf"
            options={opts}
            value={portfolioValue}
            onChange={value => portfolioSelector(value, mobileNavCollapsed)}
            placeholder="Select Portfolio"
            onInputKeyDown={event => searchPortfolioHandler(event.target.value)}
          />
When the user enters something from his keyboard the service is called successfully and my state is updating correctly. The only issue i'm facing is that when i'm giving inputs my list is not updating instantly. My list is updating when i click out of my dropdown and then click again. Here is an animated GIF for my issue.
![webp net-gifmaker 1](https://user-images.githubusercontent.com/28054369/27252150-5608c9d2-535f-11e7-9491-6492c2ab7965.gif)

**Comment by TrevorBurnham** [comment]
What's going on in that `onInputKeyDown` handler? If you remove that line, does the Select behave normally?

**Comment by alrms** [comment]
When i gave an input from my keyboard a service is called through redux saga. Am i missing a property and my list is not refreshed? It looks like even if my state is updating the list is not updating instantly. Only after onBlur and then onFocus the list is updating

**Comment by TrevorBurnham** [comment]
So you're changing `opts` in the `onInputKeyDown` handler?

Instead of using `options` and `onInputKeyDown`, have you considered using `loadOptions`? That's the official mechanism for supplying options asynchronously in response to the user's search query.

**Comment by alrms** [comment]
Hmm nice thought Trevor. I'm gonna give it a try and i 'll inform you. Close the issue if you wish to and i'm going to inform you if this approach will work properly :)

**Comment by alrms** [comment]
I've change the options to loadOptions. Now the list is not rendering at all

**Comment by TrevorBurnham** [comment]
What does your `loadOptions` function look like?

**Comment by alrms** [comment]
My loadOptions is exactly the same as my options function beacause when the service is called i save my state with the exact same way:
const clientsIdArray = Array.from(clients.keys());

    const opts = clientsIdArray.map((client) => {
      const lastName = clients.getIn([client, 'lastName']);
      const exchangeCode = clients.getIn([client, 'exchangeCode']);
      const customer = `${lastName}(${exchangeCode})`;
      const portArray = clients.getIn([client, 'portfolioCode']).toArray();
      if (portArray.find(i => i.includes('#'))) {
        portArray.push(portArray.splice(portArray.indexOf(portArray.find(i => i.includes('#'))), 1)[0]);
      }
      const typesArray = [];
      for (let i = 0; i < portArray.length; i += 1) {
        typesArray[i] = portfolios.getIn([portArray[i], 'type']);
      }
      const finalTypesArray = typesArray
        .filter(value => value !== undefined);
      if (finalTypesArray.includes('DERIV')) {
        finalTypesArray.push(finalTypesArray.splice(finalTypesArray.indexOf('DERIV'), 1)[0]);
      }
      return {
        label: customer,
        value: client,
        options: finalTypesArray.map((value, i) =>
          ({ label: value, value: portArray[i] }))
      };
    });

and then optios ={opts} or loadOptions={opts}

**Comment by alrms** [comment]
You can chech a same issue as mine. He is not using loadOptions as i see https://stackoverflow.com/questions/43072867/use-async-react-select-with-redux-saga

**Comment by TrevorBurnham** [comment]
I don't know how to help you. React Select is not a pure component. It may be fundamentally incompatible with redux-saga, unless you can interact with redux-saga through `loadOptions`.
