### ISSUE TITLE
react-select-plus + search not working with comma

### ISSUE THREAD

**Issue by ravishah990** [HubSpot/react-select-plus#81]
I am using react-select-plus control in react for drop down. When I search any data using space that's work fine. 
Now, My Issue is In data there are specific comma in that word then Isn't work.
example in search list contain comma for example ( ann, archive ) now I try to search using ( ann archive )
then ( ann, archive ) not display in result set. I need to display that result. I want ignore that comma when searching result. so that ignore comma in my search criteria and give me that data.

How, should I solve this.

Please help me.

**Comment by TrevorBurnham** [comment]
Have you tried setting the `delimiter` prop? It defaults to `','`.

**Comment by ravishah990** [comment]
no, It's solved using filter option.

**Comment by TrevorBurnham** [comment]
OK.
