### ISSUE TITLE
Request?

### ISSUE THREAD

**Issue by bradennapier** [HubSpot/react-select-plus#82]
### Thanks for using react-select!

It has become fairly common practice from what I can tell for users of CSSModules to parse .global.css and have that indicate that css modules should not be used.  It would be awesome if that were the case here so that it would be much simpler to implement the css with a simple import.  

I would think its a fairly easy thing to support and would be an appreciated feature.

Thanks a ton to everyone who maintains this.  I used the old select a ton and love what I am seeing here -- starting the path to upgrade now.

```js
{
        test: /\.global\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
      {
        test: /^((?!\.global).)*\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              camelCase: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
```

**Comment by TrevorBurnham** [comment]
You should make this request to the upstream project: https://github.com/JedWatson/react-select If they make the change there, it'll get merged in here.
