### ISSUE TITLE
Every backspace Removes  call load option method.

### ISSUE THREAD

**Issue by ravishah990** [HubSpot/react-select-plus#83]
How to call every backspace remove call load option. I am using select.Async control in every input change method call fetch method and fetch data but when I press backspace  then first time called that load option  method but in next time that can't call load option method.

` <Select.Async
onChange={this.onChange}
valueKey="placeID"
filterOptions={this.filterOptions}
labelKey="cityState"
loadOptions={this.getUsers}
onInputChange={inp => this.onInputChange(inp)}
onBlur={this.onBlur}
onInputKeyDown={inp => this.onInputKeyDown(inp)}
onFocus={this.onFocousSearch}
value={this.state.value}
searchPromptText="Please enter 3 or more characters"
loadingPlaceholder={this.state.loadingtext}
noResultsText="No results found"
options={this.state.options}
placeholder={this.state.placeholdervalue}
autoBlur

/> `

In above code in load option that get user method call. My get User method is : 
`
  getUsers = (input) => {
    console.log(input);
    if (!input) {
      return Promise.resolve({ options: [] });
    }
    if (input.length > 2) {
      const newstate = this.state;
      newstate.loadingtext = 'Searching...';
      this.setState({ newstate });
      const searchLocation = Object.assign({}, cookie.load('cLocation'));
      searchLocation.searchText = input;
      searchLocation.isBusiness = false;
      console.log(input.toString().length);
      return fetch(sourceName.searchNavbar, apiUrl.locationAndBusiness,
    searchLocation)
    .then(json => ({ options: json.data }));
    }
    return null;
  } 

`

When I click first time back space then get user method call but in second time I pressed back space then not called that get user method. How to call every backspace remove call this method.

**Comment by TrevorBurnham** [comment]
I'm having a hard time understanding your question. `loadOptions` is called every time `onInputChange` is called (unless `onInputChange` throws an error), as you can see here: https://github.com/HubSpot/react-select-plus/blob/ecab12eeb19feb0bb995a7ae92ea0d3aa2f1960e/src/Async.js#L141-L157

I hope you can find the answers you want in that source file.
