### ISSUE TITLE
React-select-plus "isLoading={true}" property is not showing the loader

### ISSUE THREAD

**Issue by alrms** [HubSpot/react-select-plus#84]
Hello everyone, i'm using react-select-plus and i use onInputChange for calling a service and fetching the options. I've read carefully the documentation and is saying that if we desire to load async options externally we should use the "isLoading" property. But when i've set it in my Select Tag it does not work.
Here is my code:
<Select
              id="portf"
              options={opts}
              isLoading={true}
              value={portfolioValue}
              onChange={value => portfolioSelector(value, mobileNavCollapsed)}
              onInputChange={value =>
                searchPortfolioHandler(value)}
            />
Do you have any idea of how to handle this? This is causing me a severe problem because even i have values in my state my list is not refreshing.

**Comment by TrevorBurnham** [comment]
`isLoading` just causes the spinner animation to appear:

### `isLoading={false}`

![without-isloading](https://user-images.githubusercontent.com/224895/28126269-00da5772-66f7-11e7-95d1-1c3b3709ca18.gif)

### `isLoading={true}`

![with-isloading](https://user-images.githubusercontent.com/224895/28126275-04beb4be-66f7-11e7-9c0b-8a7762e36c14.gif)

If the component has that prop but you don't see the spinner, then my guess would be that you don't have the relevant CSS styles loaded for the `.Select-loading-zone` and `.Select-loading` elements.
