### ISSUE TITLE
How can i choose the group title as a value?

### ISSUE THREAD

**Issue by Charlie91** [HubSpot/react-select-plus#92]
It would be awesome if somebody told me is this functionality possible or not.
I want the group parent was be able to be chosen.
So, if we had something like that:

> Fruits
>   --apples
>   --pineapples
>   --mangos
> Vegetables
>   --tomatos
>   --potato

we would choose "Fruits" and "Vegetables" as a finish results.
Thx you

**Comment by TrevorBurnham** [comment]
Sorry, groups as selectable values aren't supported. We have no plans to add this feature.
