### ISSUE TITLE
eslint-plugin-import fails on rc10 

### ISSUE THREAD

**Issue by RusAlex** [HubSpot/react-select-plus#97]
I've just created a minimal working example with travis-ci output. 

Please it. 

https://github.com/RusAlex/react-select-plus-bug

https://travis-ci.org/RusAlex/react-select-plus-bug/jobs/294442075

**Comment by RusAlex** [comment]
I tested the same version of 'react-select' there is no such bug.

**Comment by TrevorBurnham** [comment]
Ah, looks like the `package.json` [declares](https://github.com/HubSpot/react-select-plus/blob/19d023674c9d71d21a214d8bc13904dd97ad7f38/package.json#L6)

```
"jsnext:main": "dist/react-select-plus.es.js"
```

but no such file exists—it was named `react-select.es.js`, as in the upstream project. PR pending.

**Comment by TrevorBurnham** [comment]
@RusAlex Thanks for reporting! I've confirmed that this is fixed in 1.0.0-rc.10.patch1.
